name: cms-frontend

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Start app
        run: yarn start & wait-on http://localhost:3000
        # The '&' symbol is added to run the command in the background

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: yarn build
      - name: Run tests
        run: yarn cypress:run
