name: cms-frontend

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Start app
        run: yarn start &
        # The '&' symbol is added to run the command in the background
      - name: Wait for app to start
        run: |
          n=0
          until [ $n -ge 20 ]
          do
            curl -s http://localhost:3000 && break
            n=$[$n+1]
            sleep 10
          done
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: yarn build
      - name: Run tests
        run: yarn cypress:run
